### PR TITLE
FINDING-11496 Add max-age: 0 to cache-control and remove expires header

### PR DESCRIPTION
**Pull request by lilianammmatos**
> In http 1.0, expires HAD to be a date. In http 1.1, they specify that any non-date format (e.g. 0 ) should be treaded in the past. However, they also say that max-age takes precedence.
Basically, it's best if we simply include max-age=0 and not include expires.

(via [Jira ticket](https://1stdibs.atlassian.net/browse/FINDING-11496))

### CODE REVIEW

**Comment by hellatan** [comment]
@lilianammmatos can you update the test to pass?

**Comment by hellatan** [comment]
I think it's mainly removing the `Expires` field

**Comment by lilianammmatos** [comment]
@hellatan tests are passing 🎉  !

**Comment by lilianammmatos** [comment]
```
+ cache-headers@1.2.0
```

**Pull request merged**
